/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Data file for the resume generator
 */
export interface Data {
  firstName: string;
  lastName: string;
  [k: string]: unknown;
}
